package com.bpaas.doc.framework.web.pojo;

import java.io.Serializable;
import java.util.Date;

public class UcsEmployee implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.name
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.email
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.tel
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String tel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.address
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.create_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.modify_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private Date modifyDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.entry_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private Date entryDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.leave_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private Date leaveDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.birthday
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private Date birthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.sex
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.province
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String province;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.city
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String city;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.area
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String area;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.org_id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String orgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.is_incharge
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String isIncharge;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.ent_id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String entId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.status
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_employee.grade_id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	private String gradeId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.id
	 * @return  the value of ucs_employee.id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.id
	 * @param id  the value for ucs_employee.id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.name
	 * @return  the value of ucs_employee.name
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.name
	 * @param name  the value for ucs_employee.name
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.email
	 * @return  the value of ucs_employee.email
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.email
	 * @param email  the value for ucs_employee.email
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.tel
	 * @return  the value of ucs_employee.tel
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.tel
	 * @param tel  the value for ucs_employee.tel
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.address
	 * @return  the value of ucs_employee.address
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.address
	 * @param address  the value for ucs_employee.address
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.create_date
	 * @return  the value of ucs_employee.create_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.create_date
	 * @param createDate  the value for ucs_employee.create_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.modify_date
	 * @return  the value of ucs_employee.modify_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public Date getModifyDate() {
		return modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.modify_date
	 * @param modifyDate  the value for ucs_employee.modify_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.entry_date
	 * @return  the value of ucs_employee.entry_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public Date getEntryDate() {
		return entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.entry_date
	 * @param entryDate  the value for ucs_employee.entry_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.leave_date
	 * @return  the value of ucs_employee.leave_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public Date getLeaveDate() {
		return leaveDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.leave_date
	 * @param leaveDate  the value for ucs_employee.leave_date
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setLeaveDate(Date leaveDate) {
		this.leaveDate = leaveDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.birthday
	 * @return  the value of ucs_employee.birthday
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.birthday
	 * @param birthday  the value for ucs_employee.birthday
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.sex
	 * @return  the value of ucs_employee.sex
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.sex
	 * @param sex  the value for ucs_employee.sex
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.province
	 * @return  the value of ucs_employee.province
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.province
	 * @param province  the value for ucs_employee.province
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.city
	 * @return  the value of ucs_employee.city
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.city
	 * @param city  the value for ucs_employee.city
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.area
	 * @return  the value of ucs_employee.area
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.area
	 * @param area  the value for ucs_employee.area
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setArea(String area) {
		this.area = area == null ? null : area.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.org_id
	 * @return  the value of ucs_employee.org_id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.org_id
	 * @param orgId  the value for ucs_employee.org_id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId == null ? null : orgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.is_incharge
	 * @return  the value of ucs_employee.is_incharge
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getIsIncharge() {
		return isIncharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.is_incharge
	 * @param isIncharge  the value for ucs_employee.is_incharge
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setIsIncharge(String isIncharge) {
		this.isIncharge = isIncharge == null ? null : isIncharge.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.ent_id
	 * @return  the value of ucs_employee.ent_id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getEntId() {
		return entId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.ent_id
	 * @param entId  the value for ucs_employee.ent_id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setEntId(String entId) {
		this.entId = entId == null ? null : entId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.status
	 * @return  the value of ucs_employee.status
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.status
	 * @param status  the value for ucs_employee.status
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_employee.grade_id
	 * @return  the value of ucs_employee.grade_id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public String getGradeId() {
		return gradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_employee.grade_id
	 * @param gradeId  the value for ucs_employee.grade_id
	 * @mbggenerated  Mon May 21 11:02:18 CST 2018
	 */
	public void setGradeId(String gradeId) {
		this.gradeId = gradeId == null ? null : gradeId.trim();
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 8836483397367764933L;
//
	private String orgName;

    /**
     * 暂时未获取该数据
     * @return
     */
	@Deprecated
	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
}