package com.bpaas.doc.framework.web.pojo;

import java.util.Date;

public class UcsUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.id
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.username
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.password
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.salt
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.org_id
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private String orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.ent_id
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private String entId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.create_date
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.last_login_time
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.name
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.status
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.last_login_ip
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private String lastLoginIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.is_first
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	private String isFirst;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.id
	 * @return  the value of ucs_user.id
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.id
	 * @param id  the value for ucs_user.id
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.username
	 * @return  the value of ucs_user.username
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.username
	 * @param username  the value for ucs_user.username
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.password
	 * @return  the value of ucs_user.password
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.password
	 * @param password  the value for ucs_user.password
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.salt
	 * @return  the value of ucs_user.salt
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.salt
	 * @param salt  the value for ucs_user.salt
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setSalt(String salt) {
		this.salt = salt == null ? null : salt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.org_id
	 * @return  the value of ucs_user.org_id
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.org_id
	 * @param orgId  the value for ucs_user.org_id
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId == null ? null : orgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.ent_id
	 * @return  the value of ucs_user.ent_id
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public String getEntId() {
		return entId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.ent_id
	 * @param entId  the value for ucs_user.ent_id
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setEntId(String entId) {
		this.entId = entId == null ? null : entId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.create_date
	 * @return  the value of ucs_user.create_date
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.create_date
	 * @param createDate  the value for ucs_user.create_date
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.last_login_time
	 * @return  the value of ucs_user.last_login_time
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.last_login_time
	 * @param lastLoginTime  the value for ucs_user.last_login_time
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.name
	 * @return  the value of ucs_user.name
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.name
	 * @param name  the value for ucs_user.name
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.status
	 * @return  the value of ucs_user.status
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.status
	 * @param status  the value for ucs_user.status
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.last_login_ip
	 * @return  the value of ucs_user.last_login_ip
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public String getLastLoginIp() {
		return lastLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.last_login_ip
	 * @param lastLoginIp  the value for ucs_user.last_login_ip
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.is_first
	 * @return  the value of ucs_user.is_first
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public String getIsFirst() {
		return isFirst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.is_first
	 * @param isFirst  the value for ucs_user.is_first
	 * @mbggenerated  Mon Nov 20 17:09:58 CST 2017
	 */
	public void setIsFirst(String isFirst) {
		this.isFirst = isFirst == null ? null : isFirst.trim();
	}

	private String orgName;

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
}