spring:
  jms:
    # 默认情况下activemq提供的是queue模式，若要使用topic模式需要配置下面配置
    pub-sub-domain: false
  activemq:
    broker-url: tcp://localhost:61616
    # 账号
    user:  admin
    # 密码
    password: admin
#    # 在考虑结束之前等待的时间
#    close-timeout: 15s
#    # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
#    in-memory: true
#    # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
#    non-blocking-redelivery: false
#    # 等待消息发送响应的时间。设置为0等待永远。
#    send-timeout: 0
#
#    # 包
#    packages:
#      # 是否信任所有包
#      trust-all: true
#      # 要信任的特定包的逗号分隔列表（当不信任所有包时）
#      trusted:
#
#    # 连接池
#    pool:
#     # 当连接请求和池满时是否阻塞。设置false会抛“JMSException异常”。
#     block-if-full: true
#     # 如果池仍然满，则在抛出异常前阻塞时间。
#     block-if-full-timeout: -1ms
#     # 是否在启动时创建连接。可以在启动时用于加热池。
#     create-connection-on-startup: true
#     # 是否用Pooledconnectionfactory代替普通的ConnectionFactory。
#     enabled: false
#     # 连接过期超时。
#     expiry-timeout: 0ms
#     # 连接空闲超时
#     idle-timeout: 30s
#     # 连接池最大连接数
#     max-connections: 1
#     # 每个连接的有效会话的最大数目。
#     maximum-active-session-per-connection: 500
#     # 当有"JMSException"时尝试重新连接
#     reconnect-on-exception: true
#     # 在空闲连接清除线程之间运行的时间。当为负数时，没有空闲连接驱逐线程运行。
#     time-between-expiration-check: -1ms
#     # 是否只使用一个MessageProducer
#     use-anonymous-producers: true

activemq_1:
  url:
  username:
  password:
