server:
  session-timeout: 1800
  port: 80

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: ${ENV:dev}
  mail:
    #邮箱服务器地址
    #QQ smtp.qq.com       Sina smtp.sina.cn
    #Aliyun smtp.aliyun.com  163 smtp.163.com
    host: smtp.sina.cn
    #邮箱用户名
    username: hanxinghua2015@sina.com
    #邮箱密码（注意：QQ邮箱应该使用授权码）
    password: XXX
    #编码格式
    default-encoding: UTF-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.hanxiaozhang.**.domain
#配置打印日志
logging:
  level:
    #root日志输出级别
    root: info
    #应用的包下日志输出输出级别
    com.hanxiaozhang: debug

mail:
  fromMail:
    #发送邮件地址
    sender: hanxinghua2015@sina.com