server:
  session-timeout: 1800
  port: 80

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent_output: true
  profiles:
    active: ${ENV:dev}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.hanxiaozhang.**.domain
# 配置打印日志
logging:
  level:
    # root日志输出级别
    root: info
    # 应用的包下日志输出输出级别
    com.hanxiaozhang: debug
# actuator
management:
#  server:
#    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
async:
  executor:
    core-pool-size: 10
    max-pool-size: 10
    queue-capacity: 100
    await-termination-seconds: 60
    wait-for-tasks-to-complete-on-shutdown: true
    thread-name-prefix: AsyncExecutorThread-
